### ISSUE TITLE
Error while running toyfs.py

### ISSUE THREAD

**Issue by rajedan** [gnurag/toyfs#1]
getting error as :

File "/home/user/toyfs/toy.py", line 6, in <module>
    class ToyStat(fuse.Stat):
AttributeError: 'module' object has no attribute 'Stat'

PS: I have already installed the below packages in my ubuntu 18.04:
sudo apt-get install fuse python-fuse

**Comment by gnurag** [comment]
@rajedan, the Fuse driver is packaged as `fuse-python `in Fedora based distributions. I'm unsure if `python-fuse` that's available in Ubuntu is the same package. Would it be possible for you to verify if they're the same packages?

**Comment by viveknigam3003** [comment]
The command `python toyfs.py tmp/` worked fine the first time. The next time I tried to run it, I got the same error in the terminal. Here `tmp/` is the mount point inside my `toyfs` folder

```BASH
(fusepyenv) vivek@vivek-VirtualBox:~/Desktop/toyfs$ python toyfs.py tmp/
Traceback (most recent call last):
  File "toyfs.py", line 8, in <module>
    import toy
  File "/home/vivek/Desktop/toyfs/toy.py", line 6, in <module>
    class ToyStat(fuse.Stat):
AttributeError: module 'fuse' has no attribute 'Stat'
```

**Comment by viveknigam3003** [comment]
Before this error, I received this error:
```BASH
(fusepyenv) vivek@vivek-VirtualBox:~/Desktop/toyfs$ python toyfs.py tmp/
Traceback (most recent call last):
  File "toyfs.py", line 8, in <module>
    import toy
  File "/home/vivek/Desktop/toyfs/toy.py", line 26
    st.st_mode = stat.S_IFDIR | 0755
                                   ^
SyntaxError: invalid token
```

But this was resolved by prefixing the octal numbers with `0o` as suggested [here](https://github.com/jose1711/duplicity-fuse/pull/6) for python3 like
```PYTHON
st.st_mode = stat.S_IFDIR | 0o755
```

Any guess how these two can be resolved?

**Comment by gnurag** [comment]
@viveknigam3003 Perhaps it is time to port this project to support Python3.
